openapi: 3.0.0
info:
  title: Cattleya API
  version: 1.0.0
paths:
  /users: 
    get:
      summary: Retrieves a list of users
      responses:
        '200': 
          description: OK
          content: 
            application/json: 
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/User'

components:
  schemas:
    Todo:
      type: object
      properties:
        id: 
          type: integer
        task:
          type: string
        completed:
          type: boolean 

